# Dynamo_ExistingGondolaPlacement
# Revit 2025 / Dynamo CPython3 compatible
#
# Version 2026-10-05m-original-files
# Original File2 placement (CAD offset always on). Only orientation
# reading and Existing-view lock are changed.
#
# PURPOSE
# -------
# Places existing-condition gondolas from the JSON generated by
# Gondola_OrientationDetector.py.
#
# IMPORTANT ORIENTATION CHANGE
# ----------------------------
# The JSON should ideally contain:
#
#   "orientation": "HORIZONTAL"
#   "angle": 90.0
#
# or:
#
#   "orientation": "VERTICAL"
#   "angle": 0.0
#
# If "angle" exists, the script uses the ACTUAL angle from the DXF.
# It no longer assumes that every horizontal gondola should simply
# be rotated 90 degrees.
#
# The angle is assumed to be DEGREES measured counter-clockwise
# from the Revit X axis.
#
# If the JSON does not contain "angle", the script falls back to
# HORIZONTAL = 90 degrees and VERTICAL = 0 degrees.


import clr
import os
import json
import math


# ===========================================================================
# REVIT REFERENCES
# ===========================================================================

clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import (
    FilteredElementCollector,
    FamilySymbol,
    FamilyInstance,
    Transaction,
    XYZ,
    Level,
    ViewPlan,
    Line,
    ElementTransformUtils,
    Phase,
    BuiltInParameter,
    OverrideGraphicSettings,
    Color,
    ImportInstance
)

from Autodesk.Revit.DB.Structure import StructuralType
from RevitServices.Persistence import DocumentManager


# ===========================================================================
# SETTINGS
# ===========================================================================

JSON_PATH = r"C:\Users\msharan\OneDrive - Kmart Australia Limited\Desktop\Stores Foundry\Tracing\json\gondola_data_Marrickville_New4.json"

LEVEL_NAME = "00-GROUND"
VIEW_NAME = "1.0 EXISTING CONDITIONS - GROUND"
SCRIPT_VERSION = "2026-10-05m-original-files"

# Partial CAD import name.
# Leave "" to automatically use the first suitable CAD import.
CAD_LINK_NAME = ""

MM_TO_FT = 1.0 / 304.8

# ---------------------------------------------------------------------------
# ORIENTATION SETTINGS
# ---------------------------------------------------------------------------

# True:
#     use the "angle" value from JSON whenever available.
#
# False:
#     ignore JSON angle and use the fallback orientation.
USE_JSON_ANGLE = True

# JSON angle convention:
#
#   0°   = Revit +X
#   90°  = Revit +Y
#   180° = Revit -X
#   270° = Revit -Y
#
# If your detector outputs the angle in the opposite direction,
# change ANGLE_SIGN to -1.
ANGLE_SIGN = 1.0

# If the detector's angle is relative to the CAD/DXF X-axis rather
# than Revit's X-axis, this offset can be adjusted.
#
# Normally leave this at 0.
ANGLE_OFFSET_DEG = 0.0

# Fallback when JSON has no usable angle.
VERTICAL_FALLBACK_DEG = 0.0
HORIZONTAL_FALLBACK_DEG = 90.0

# ---------------------------------------------------------------------------
# POSITION SETTINGS
# ---------------------------------------------------------------------------

# If the JSON coordinates already represent Revit coordinates,
# leave this False.
#
# If JSON coordinates are local CAD coordinates and the CAD import
# has a translation offset, set this True.
APPLY_CAD_TRANSLATION = True

# If the JSON coordinates were generated in CAD local coordinates
# but the CAD import also has rotation, this setting allows the
# CAD transform to be applied.
#
# Leave False initially unless your DXF was imported with rotation.
APPLY_CAD_ROTATION = False


# ===========================================================================
# FAMILY / TYPE MAP
# ===========================================================================
#
# KEEP YOUR EXISTING TYPE_MAP HERE.
#
# ---------------------------------------------------------------------------
# PASTE YOUR COMPLETE TYPE_MAP FROM THE ORIGINAL SCRIPT BELOW THIS LINE.
# ---------------------------------------------------------------------------

TYPE_MAP = {

    # 15F Standard
    "15FLCA": ("Floor_Gondola", "15FLCA"),
    "15FLCS": ("Floor_Gondola", "15FLCS"),
    "15FLOA": ("Floor_Gondola", "15FLOA"),
    "15FLOS": ("Floor_Gondola", "15FLOS"),
    "15FMCA": ("Floor_Gondola", "15FMCA"),
    "15FMCS": ("Floor_Gondola", "15FMCS"),
    "15FMOA": ("Floor_Gondola", "15FMOA"),
    "15FMOS": ("Floor_Gondola", "15FMOS"),

    # 18F
    "18FLCA": ("Floor_Gondola", "18FLCA"),
    "18FLCS": ("Floor_Gondola", "18FLCS"),
    "18FMCA": ("Floor_Gondola", "18FMCA"),
    "18FMCS": ("Floor_Gondola", "18FMCS"),
    "18FMOA": ("Floor_Gondola", "18FMOA"),
    "18FMOS": ("Floor_Gondola", "18FMOS"),

    # 21F
    "21FLCA": ("Floor_Gondola", "21FLCA"),
    "21FLCS": ("Floor_Gondola", "21FLCS"),
    "21FLOA": ("Floor_Gondola", "21FLOA"),
    "21FLOS": ("Floor_Gondola", "21FLOS"),
    "21FMCA": ("Floor_Gondola", "21FMCA"),
    "21FMCS": ("Floor_Gondola", "21FMCS"),
    "21FMOA": ("Floor_Gondola", "21FMOA"),
    "21FMOS": ("Floor_Gondola", "21FMOS"),

    # 34F
    "34FLCA": ("Floor_Gondola", "34FLCA"),
    "34FLCS": ("Floor_Gondola", "34FLCS"),
    "34FLOA": ("Floor_Gondola", "34FLOA"),
    "34FLOS": ("Floor_Gondola", "34FLOS"),
    "34FMCA": ("Floor_Gondola", "34FMCA"),
    "34FMCS": ("Floor_Gondola", "34FMCS"),
    "34FMOA": ("Floor_Gondola", "34FMOA"),
    "34FMOS": ("Floor_Gondola", "34FMOS"),

    # 34H
    "34HLCA": ("Floor_Gondola_High_Bay", "34HLCA"),
    "34HLCS": ("Floor_Gondola_High_Bay", "34HLCS"),
    "34HLOA": ("Floor_Gondola_High_Bay", "34HLOA"),
    "34HLOS": ("Floor_Gondola_High_Bay", "34HLOS"),

    # 27H
    "27HLCA": ("Floor_Gondola_High_Bay", "27HLCA"),
    "27HLCS": ("Floor_Gondola_High_Bay", "27HLCS"),

    # 34S
    "34SLCA": ("Floor_Gondola", "34FLCA EXTENSION LEG"),
    "34SLCS": ("Floor_Gondola", "34FLCS"),

    # 34RD
    "34RDLC": ("End_Panel_Decks", "34ELO"),
    "FLATDECK": ("Decks_&_Hopper", "LRD"),
    "FLATDECKWS": ("Decks_&_Hopper", "LRD_2S"),

    # 36W
    "36WLOA": ("Wall_Gondola", "36WLOA"),
    "36WLOS": ("Wall_Gondola", "36WLOS"),
    "36WLCA": ("Wall_Gondola", "36WLCA"),
    "36WLCS": ("Wall_Gondola", "36WLCS"),
    "15WLOS": ("Wall_Gondola", "15WLOS"),

    # 36B
    "36BLOA": ("Floor_Gondola_High_Bay", "36HLOA"),
    "36BLOS": ("Wall_Gondola_High_Bay", "36HLOS"),
    "36BLCA": ("Floor_Gondola_High_Bay", "36HLCA"),
    "36BLCS": ("Wall_Gondola_High_Bay", "36HLCS"),

    # 15W
    "15WLCA": ("Wall_Gondola", "15WLCA"),
    "15WLCS": ("Wall_Gondola", "15WLCS"),
    "15WLOS": ("Wall_Gondola", "15WLOS"),
    "15WMCA": ("Wall_Gondola", "15WMCA"),
    "15WMCS": ("Wall_Gondola", "15WMCS"),

    # 12W
    "12WMCA": ("Wall_Gondola", "12WMCA"),
    "12WMCS": ("Wall_Gondola", "12WMCS"),

    # WA / WS
    "15FMWA": ("Floor_Gondola", "15FMWA"),
    "15FMWS": ("Floor_Gondola", "15FMWS"),
    "21FMWA": ("Floor_Gondola", "21FMWA"),
    "21FMWS": ("Floor_Gondola", "21FMWS"),
    "34FMWA": ("Floor_Gondola", "34FMWA"),
    "34FMWS": ("Floor_Gondola", "34FMWS"),

    # 12F
    "12FLCA": ("Floor_Gondola", "12FLCA"),
    "12FLCS": ("Floor_Gondola", "12FLCS"),
    "12FLOA": ("Floor_Gondola", "12FLOA"),
    "12FLOS": ("Floor_Gondola", "12FLOS"),
    "12FMCA": ("Floor_Gondola", "12FMCA"),
    "12FMCS": ("Floor_Gondola", "12FMCS"),
    "12FMOA": ("Floor_Gondola", "12FMOA"),
    "12FMOS": ("Floor_Gondola", "12FMOS"),

    # 36
    "36HLCA": ("Floor_Gondola_High_Bay", "36HLCA"),
    "36HLCS": ("Floor_Gondola_High_Bay", "36HLCS"),
    "36HLOA": ("Floor_Gondola_High_Bay", "36HLOA"),
    "36HLOS": ("Floor_Gondola_High_Bay", "36HLOS"),

    # 34W
    "34WLOA": ("Wall_Gondola", "34WLOA"),
    "34WLOS": ("Wall_Gondola", "34WLOS"),
    "34WLCA": ("Wall_Gondola", "34WLCA"),
    "34WLCS": ("Wall_Gondola", "34WLCS"),

    # 32W
    "32WLOA": ("Wall_Gondola", "32WLOA"),
    "32WLOS": ("Wall_Gondola", "32WLOS"),
    "32WLCA": ("Wall_Gondola", "32WLCA"),
    "32WLCS": ("Wall_Gondola", "32WLCS"),

    # 30W
    "30WLOA": ("Wall_Gondola", "30WLOA"),
    "30WLOS": ("Wall_Gondola", "30WLOS"),
    "30WLCA": ("Wall_Gondola", "30WLCA"),
    "30WLCS": ("Wall_Gondola", "30WLCS"),

    # 27W
    "27WLOA": ("Wall_Gondola", "27WLOA"),
    "27WLOS": ("Wall_Gondola", "27WLOS"),
    "27WLCA": ("Wall_Gondola", "27WLCA"),
    "27WLCS": ("Wall_Gondola", "27WLCS"),

    # 21W
    "21WLOA": ("Wall_Gondola", "21WLOA"),
    "21WLOS": ("Wall_Gondola", "21WLOS"),
    "21WLCA": ("Wall_Gondola", "21WLCA"),
    "21WLCS": ("Wall_Gondola", "21WLCS"),

    # END PANELS
    "12DELC": ("End_Panel", "12DELC"),
    "12DEMO": ("End_Panel", "12DEMO"),
    "12ELC": ("End_Panel", "12ELC"),
    "12ELO": ("End_Panel", "12ELO"),
    "12EMC": ("End_Panel", "12EMC"),
    "12EMO": ("End_Panel", "12EMO"),
    "12SELC": ("End_Panel", "12SELC"),
    "12SEMC": ("End_Panel", "12SEMC"),

    "15DELC": ("End_Panel", "15DELC"),
    "15DELO": ("End_Panel", "15DELO"),
    "15DEMC": ("End_Panel", "15DEMC"),
    "15DEMO": ("End_Panel", "15DEMO"),
    "15ELC": ("End_Panel", "15ELC"),
    "15ELO": ("End_Panel", "15ELO"),
    "15ELW": ("End_Panel", "15ELW"),
    "15EMC": ("End_Panel", "15EMC"),
    "15EMM": ("End_Panel", "15EMM"),
    "15EMO": ("End_Panel", "15EMO"),
    "15EMW": ("End_Panel", "15EMW"),
    "15SELC": ("End_Panel", "15SELC"),
    "15SELO": ("End_Panel", "15SELO"),
    "15SEMC": ("End_Panel", "15SEMC"),
    "15SEMO": ("End_Panel", "15SEMO"),
    "15SEMW": ("End_Panel", "15SEMW"),

    "18DELC": ("End_Panel", "18DELC"),
    "18DEMO": ("End_Panel", "18DEMO"),
    "18DEMC": ("End_Panel", "18DEMC"),
    "18ELC": ("End_Panel", "18ELC"),
    "18ELM": ("End_Panel", "18ELM"),
    "18ELO": ("End_Panel", "18ELO"),
    "18EMC": ("End_Panel", "18EMC"),
    "18EMM": ("End_Panel", "18EMM"),
    "18EMO": ("End_Panel", "18EMO"),
    "18POSTER END": ("End_Panel", "18POSTER END"),
    "18SELC": ("End_Panel", "18SELC"),
    "18SELO": ("End_Panel", "18SELO"),
    "18SEMC": ("End_Panel", "18SEMC"),
    "18SEMO": ("End_Panel", "18SEMO"),

    "21DELC": ("End_Panel", "21DELC"),
    "21DELC 200 PEG": ("End_Panel", "21DELC 200 PEG"),
    "21DELM": ("End_Panel", "21DELM"),
    "21DELO": ("End_Panel", "21DELO"),
    "21DEMC": ("End_Panel", "21DEMC"),
    "21DEMO": ("End_Panel", "21DEMO"),
    "21ELC": ("End_Panel", "21ELC"),
    "21ELM": ("End_Panel", "21ELM"),
    "21ELO": ("End_Panel", "21ELO"),
    "21ELW": ("End_Panel", "21ELW"),
    "21ELWM": ("End_Panel", "21ELWM"),
    "21EMC": ("End_Panel", "21EMC"),
    "21EMM": ("End_Panel", "21EMM"),
    "21EMO": ("End_Panel", "21EMO"),
    "21EMW": ("End_Panel", "21EMW"),
    "21EMWM": ("End_Panel", "21EMWM"),
    "21POSTER END": ("End_Panel", "21POSTER END"),
    "21SELC": ("End_Panel", "21SELC"),
    "21SELO": ("End_Panel", "21SELO"),
    "21SELW": ("End_Panel", "21SELW"),
    "21SEMC": ("End_Panel", "21SEMC"),
    "21SEMO": ("End_Panel", "21SEMO"),
    "21SEMW": ("End_Panel", "21SEMW"),

    "26DELW - DIVIDING WALL - END": (
        "End_Panel",
        "26DELW - DIVIDING WALL - END"
    ),

    "26EMW - DIVIDING WALL EPF": (
        "End_Panel",
        "26EMW - DIVIDING WALL EPF"
    ),

    "27ELC": ("End_Panel", "27ELC"),
    "27ELO": ("End_Panel", "27ELO"),
    "27ELW": ("End_Panel", "27ELW"),
    "27EMC": ("End_Panel", "27EMC"),
    "27EMO": ("End_Panel", "27EMO"),
    "27POSTER 540 END": ("End_Panel", "27POSTER 540 END"),
    "27SELC": ("End_Panel", "27SELC"),
    "27SELO": ("End_Panel", "27SELO"),
    "27SELW": ("End_Panel", "27SELW"),

    "30DELO": ("End_Panel", "30DELO"),
    "30DEMC": ("End_Panel", "30DEMC"),
    "30DEMO": ("End_Panel", "30DEMO"),
    "30ELC": ("End_Panel", "30ELC"),
    "30ELM": ("End_Panel", "30ELM"),
    "30ELO": ("End_Panel", "30ELO"),
    "30EMC": ("End_Panel", "30EMC"),
    "30EMM": ("End_Panel", "30EMM"),
    "30EMO": ("End_Panel", "30EMO"),
    "30SELC": ("End_Panel", "30SELC"),
    "30SELO": ("End_Panel", "30SELO"),
    "30SELW": ("End_Panel", "30SELW"),
    "30SEMC": ("End_Panel", "30SEMC"),
    "30SEMO": ("End_Panel", "30SEMO"),

    "32DELC": ("End_Panel", "32DELC"),
    "32DELO": ("End_Panel", "32DELO"),
    "32DEMC": ("End_Panel", "32DEMC"),
    "32DEMO": ("End_Panel", "32DEMO"),
    "32ELC": ("End_Panel", "32ELC"),
    "32ELM": ("End_Panel", "32ELM"),
    "32ELO": ("End_Panel", "32ELO"),
    "32ELW": ("End_Panel", "32ELW"),
    "32ELWM": ("End_Panel", "32ELWM"),
    "32EMC": ("End_Panel", "32EMC"),
    "32EMM": ("End_Panel", "32EMM"),
    "32EMO": ("End_Panel", "32EMO"),
    "32EMW": ("End_Panel", "32EMW"),
    "32EMWM": ("End_Panel", "32EMWM"),
    "32SELC": ("End_Panel", "32SELC"),
    "32SELO": ("End_Panel", "32SELO"),
    "32SELW": ("End_Panel", "32SELW"),
    "32SEMC": ("End_Panel", "32SEMC"),
    "32SEMO": ("End_Panel", "32SEMO"),
    "32SEMW": ("End_Panel", "32SEMW"),

    "34DELC": ("End_Panel", "34DELC"),
    "34DELO": ("End_Panel", "34DELO"),
    "34DEMC": ("End_Panel", "34DEMC"),
    "34DEMO": ("End_Panel", "34DEMO"),
    "34ELC": ("End_Panel", "34ELC"),
    "34ELM": ("End_Panel", "34ELM"),
    "34ELO": ("End_Panel", "34ELO"),
    "34ELW": ("End_Panel", "34ELW"),
    "34ELWM": ("End_Panel", "34ELWM"),
    "34EMC": ("End_Panel", "34EMC"),
    "34EMM": ("End_Panel", "34EMM"),
    "34EMO": ("End_Panel", "34EMO"),
    "34EMW": ("End_Panel", "34EMW"),
    "34EMWM": ("End_Panel", "34EMWM"),
    "34SELC": ("End_Panel", "34SELC"),
    "34SELO": ("End_Panel", "34SELO"),
    "34SELW": ("End_Panel", "34SELW"),
    "34SEMC": ("End_Panel", "34SEMC"),
    "34SEMO": ("End_Panel", "34SEMO"),
    "34SEMW": ("End_Panel", "34SEMW"),
    "34SELW 540 END": ("End_Panel", "34SELW 540 END"),
    "34SEMV 540 END": ("End_Panel", "34SEMV 540 END"),

    "HALLMARK END 1200": ("End_Panel", "HALLMARK END 1200"),
    "HALLMARK END 900": ("End_Panel", "HALLMARK END 900"),

    "12QMCA": ("Floor_Gondola_Queuing", "12QMCA"),
    "12QMCS": ("Floor_Gondola_Queuing", "12QMCS"),

    #OLD VS new Codes
    "15EPLC": ("End_Panel", "15ELC"),
"15EPMC": ("End_Panel", "15EMC"),
"15EPMO": ("End_Panel", "15EMO"),
"15EPLO": ("End_Panel", "15ELO"),
"15EPMM": ("End_Panel", "15EMM"),

"15SHMC": ("End_Panel", "15SEMC"),
"15SHLC": ("End_Panel", "15SELC"),
"15SHLO": ("End_Panel", "15SELO"),

"18EPLC": ("End_Panel", "18ELC"),
"18EPMC": ("End_Panel", "18EMC"),
"18EPMO": ("End_Panel", "18EMO"),
"18EPLO": ("End_Panel", "18ELO"),
"18EPMM": ("End_Panel", "18EMM"),

"18SHMC": ("End_Panel", "18SEMC"),
"18SHLC": ("End_Panel", "18SELC"),
"18SHLO": ("End_Panel", "18SELO"),

"21EPLC": ("End_Panel", "21ELC"),
"21EPMC": ("End_Panel", "21EMC"),
"21EPMO": ("End_Panel", "21EMO"),
"21EPLO": ("End_Panel", "21ELO"),
"21EPMM": ("End_Panel", "21EMM"),
"21SHMC": ("End_Panel", "21SEMC"),
"21SHLC": ("End_Panel", "21SELC"),
"21SHLO": ("End_Panel", "21SELO"),

"27HLO": ("End_Panel", "27SELOS"),

"32EPLC": ("End_Panel", "32EMC"),
"32EPMC": ("End_Panel", "32EMC"),
"32EPMO": ("End_Panel", "32EMO"),
"32EPLO": ("End_Panel", "32ELO"),
"32SHLO": ("End_Panel", "32SELO"),

"34EPLC": ("End_Panel", "34EMC"),
"34EPMC": ("End_Panel", "34EMC"),
"34EPMO": ("End_Panel", "34EMO"),
"34EPLO": ("End_Panel", "34ELO"),
"34SHLO": ("End_Panel", "34SELO"),


"34BLOA": ("Wall_Gondola_High_Bay", "34HLCA OUTRIGGER POST ADDED"),
"34BLOS": ("Wall_Gondola_High_Bay", "34HLCS"),

"36BLOA": ("Wall_Gondola_High_Bay", "36HLCA OUTRIGGER POST ADDED"),
"36BLOS": ("Wall_Gondola_High_Bay", "36HLCS"),

"15RDLC":("End_Panel_Decks","15ELC (End_Panel_Decks)"),
"15RDLO":("End_Panel_Decks","15ELO (End_Panel_Decks)"),
"15RDMC":("End_Panel_Decks","15EMC(End_Panel_Decks)"),
"15RDMO":("End_Panel_Decks","15EMO(End_Panel_Decks)"),

"18RDLC":("End_Panel_Decks","18ELC(End_Panel_Decks)"),
"18RDLO":("End_Panel_Decks","18ELO(End_Panel_Decks)"),
"18RDMC":("End_Panel_Decks","18EMC(End_Panel_Decks)"),
"18RDMO":("End_Panel_Decks","18EMO(End_Panel_Decks)"),

"21RDLC":("End_Panel_Decks","21ELC(End_Panel_Decks)"),
"21RDLO":("End_Panel_Decks","21ELO(End_Panel_Decks)"),
"21RDMC":("End_Panel_Decks","21EMC(End_Panel_Decks)"),
"21RDMO":("End_Panel_Decks","21EMO(End_Panel_Decks)"),

"32RDLC":("End_Panel_Decks","32ELC(End_Panel_Decks)"),
"32RDLO":("End_Panel_Decks","32ELO(End_Panel_Decks)"),
"32RDMC":("End_Panel_Decks","32EMC(End_Panel_Decks)"),
"32RDMO":("End_Panel_Decks","32EMO(End_Panel_Decks)"),

"34RDLC":("End_Panel_Decks","34ELC(End_Panel_Decks)"),
"34RDLO":("End_Panel_Decks","34ELO(End_Panel_Decks)"),
"34RDMC":("End_Panel_Decks","34EMC(End_Panel_Decks)"),
"34RDMO":("End_Panel_Decks","34EMO(End_Panel_Decks)"),
"34RELO":("End_Panel_Decks","34ELO(End_Panel_Decks)"),

"FLATDECK W/-SURROUND":("Decks_&_Hopper","LRD_2S"),
"FLATDECK":("Decks_&_Hopper","LRD_2"),
"DECK TABLE":("Decks_&_Hopper","Deck_Table"),
"HOPPER UNIT 2150H":("Decks_&_Hopper","HOP21"),


"HOT SPOT 1500H":("Hotspots","15H Hotspot"),
"HOT SPOT COOKBOOKS":("Hotspots","15H Cookbook"),
"HOT SPOT 2100H":("Hotspots","21H Hotspot"),
"HOT SPOT 3000H":("Hotspots","30H Hotspot"),
"HOT SPOT 3200H":("Hotspots","32H Hotspot"),
"HOT SPOT 3400H":("Hotspots","34H Hotspot"),

"Straight rail":("Hotspots","racking-straight rail"),

"6Way":("Hotspots","Racking-6_Way"),
"16_Way":("Hotspots","Racking-16_Way"),

"T2 TABLE":("Hotspots","T2 VM RAIL + DISPLAY ARM (TABLE_T)"),
"T2 ARM ONLY":("Hotspots","T2 TABLE ARM ONLY"),

"HANGER TOTEM":("Hotspots","HANGER (Bin_240L)"),

}

TYPE_MAP = {
    str(code).upper().strip(): mapping
    for code, mapping in TYPE_MAP.items()
}


# ===========================================================================
# SAFE REVIT HELPERS
# ===========================================================================

def safe_element_name(element):

    if element is None:
        return ""

    try:
        value = element.Name
        if value:
            return str(value)
    except Exception:
        pass

    try:
        p = element.get_Parameter(
            BuiltInParameter.SYMBOL_NAME_PARAM
        )

        if p is not None:
            value = p.AsString()

            if value:
                return value

    except Exception:
        pass

    return ""


def safe_family_name(symbol):

    if symbol is None:
        return ""

    try:
        value = symbol.FamilyName

        if value:
            return str(value)

    except Exception:
        pass

    try:
        family = symbol.Family

        if family is not None:

            try:
                value = family.Name

                if value:
                    return str(value)

            except Exception:
                pass

    except Exception:
        pass

    return ""


def safe_symbol_name(symbol):

    if symbol is None:
        return ""

    try:
        value = symbol.Name

        if value:
            return str(value)

    except Exception:
        pass

    try:
        p = symbol.get_Parameter(
            BuiltInParameter.SYMBOL_NAME_PARAM
        )

        if p is not None:

            value = p.AsString()

            if value:
                return value

    except Exception:
        pass

    return ""


def safe_element_id_value(element_id):

    if element_id is None:
        return None

    try:
        return int(element_id.Value)
    except Exception:
        pass

    try:
        return int(element_id.IntegerValue)
    except Exception:
        pass

    try:
        return int(str(element_id))
    except Exception:
        return None


def get_instance_family_name(instance):

    if instance is None:
        return ""

    try:
        return safe_family_name(instance.Symbol)
    except Exception:
        return ""


# ===========================================================================
# ORIENTATION HELPERS
# ===========================================================================

def normalize_angle(angle):

    """
    Normalize angle into 0 <= angle < 360.
    """

    try:
        angle = float(angle)
    except Exception:
        return None

    angle = angle % 360.0

    if angle < 0:
        angle += 360.0

    return angle


def get_json_angle(g):

    """
    Read the actual angle from JSON.

    Supported keys:

        angle
        rotation
        rotation_angle
        angle_deg
        orientation_angle

    Returns None if no valid angle exists.
    """

    # Original File2 read "rotation" first. DXF text rotation is
    # almost always 0, so every family landed at 0°. Use the
    # detector's family rotation only.
    possible_keys = [
        "revit_angle",
        "angle",
        "orientation_angle",
    ]

    for key in possible_keys:

        value = g.get(key, None)

        if value is None:
            continue

        try:

            angle = float(value)
            if key == "orientation_angle":
                folded = angle % 180.0
                if folded < 0:
                    folded += 180.0
                if abs(folded - 180.0) < 1e-6:
                    folded = 0.0
                angle = (folded + 90.0) % 180.0
                if abs(angle - 180.0) < 1e-6:
                    angle = 0.0

            return normalize_angle(
                angle * ANGLE_SIGN
                + ANGLE_OFFSET_DEG
            )

        except Exception:
            pass

    return None


def get_orientation(g):

    """
    Determine the orientation and actual rotation angle.

    Priority:

        1. JSON angle
        2. orientation string
        3. vertical fallback
    """

    orientation = str(
        g.get(
            "orientation",
            ""
        )
    ).upper().strip()

    json_angle = None

    if USE_JSON_ANGLE:
        json_angle = get_json_angle(g)

    if json_angle is not None:

        return (
            orientation if orientation else "ANGLE",
            json_angle,
            "JSON angle"
        )

    if orientation == "HORIZONTAL":

        return (
            "HORIZONTAL",
            normalize_angle(
                HORIZONTAL_FALLBACK_DEG
            ),
            "fallback"
        )

    if orientation == "VERTICAL":

        return (
            "VERTICAL",
            normalize_angle(
                VERTICAL_FALLBACK_DEG
            ),
            "fallback"
        )

    return (
        orientation if orientation else "UNKNOWN",
        normalize_angle(
            VERTICAL_FALLBACK_DEG
        ),
        "fallback"
    )


# ===========================================================================
# READ JSON
# ===========================================================================

if not os.path.isfile(JSON_PATH):

    OUT = (
        "JSON NOT FOUND:\n\n{}"
    ).format(
        JSON_PATH
    )

    raise FileNotFoundError(OUT)


with open(
    JSON_PATH,
    "r"
) as f:

    data = json.load(f)


gondolas = data.get(
    "gondolas",
    []
)


# ===========================================================================
# CONNECT TO REVIT
# ===========================================================================

doc = DocumentManager.Instance.CurrentDBDocument

if doc is None:

    raise Exception(
        "Could not obtain current Revit document."
    )


# ===========================================================================
# FIND CAD IMPORT
# ===========================================================================

cad_offset_x = 0.0
cad_offset_y = 0.0

cad_rotation_rad = 0.0

cad_offset_info = (
    "No CAD transform found. "
    "Using origin (0,0)."
)

all_cad_found = []


all_imports = list(
    FilteredElementCollector(doc)
    .OfClass(ImportInstance)
)


selected_import = None


for imp in all_imports:

    try:

        sym = doc.GetElement(
            imp.GetTypeId()
        )

        cad_name_str = ""

        try:

            p = sym.get_Parameter(
                BuiltInParameter.IMPORT_SYMBOL_NAME
            )

            if p is not None:

                cad_name_str = (
                    p.AsString()
                    or ""
                )

        except Exception:
            pass


        if not cad_name_str:

            cad_name_str = safe_element_name(sym)


        if not cad_name_str:

            continue


        transform = imp.GetTotalTransform()

        origin = transform.Origin

        ox = origin.X
        oy = origin.Y


        # ---------------------------------------------------------------
        # Extract X-axis direction from CAD transform
        # ---------------------------------------------------------------

        bx = transform.BasisX

        cad_angle = math.atan2(
            bx.Y,
            bx.X
        )


        try:

            link_type = (
                "Link"
                if imp.IsLinked
                else "Import"
            )

        except Exception:

            link_type = "Import"


        all_cad_found.append(
            "    [{}] {} | "
            "offset=({:.0f},{:.0f}) mm | "
            "rotation={:.3f}°".format(
                link_type,
                cad_name_str,
                ox * 304.8,
                oy * 304.8,
                math.degrees(cad_angle)
            )
        )


        # ---------------------------------------------------------------
        # Select CAD
        # ---------------------------------------------------------------

        if CAD_LINK_NAME:

            if (
                CAD_LINK_NAME.lower()
                not in cad_name_str.lower()
            ):

                continue

        lowered = cad_name_str.lower()
        is_proposed_cad = (
            "propos" in lowered
            or "selling floor" in lowered
        )
        is_existing_cad = (
            "existing" in lowered
            and "condition" in lowered
        )
        if is_proposed_cad and not is_existing_cad:
            continue

        info_text = (
            "[{}] {} | "
            "offset=({:.3f},{:.3f}) ft "
            "= ({:.0f},{:.0f}) mm | "
            "rotation={:.3f}°"
        ).format(
            link_type,
            cad_name_str,
            ox,
            oy,
            ox * 304.8,
            oy * 304.8,
            math.degrees(cad_angle)
        )

        if selected_import is None:

            selected_import = imp

            cad_offset_x = ox
            cad_offset_y = oy

            cad_rotation_rad = cad_angle

            cad_offset_info = info_text

        if is_existing_cad:

            selected_import = imp

            cad_offset_x = ox
            cad_offset_y = oy

            cad_rotation_rad = cad_angle

            cad_offset_info = info_text

    except Exception as ex:

        all_cad_found.append(
            "    CAD ERROR: {}".format(
                str(ex)
            )
        )


# ===========================================================================
# FAMILY SYMBOL LOOKUP
# ===========================================================================

all_symbols = list(
    FilteredElementCollector(doc)
    .OfClass(FamilySymbol)
)


symbol_lookup = {}

symbol_errors = []


for s in all_symbols:

    try:

        family_name = safe_family_name(s)

        type_name = safe_symbol_name(s)

        if family_name and type_name:

            symbol_lookup[
                (family_name, type_name)
            ] = s

    except Exception as ex:

        symbol_errors.append(
            str(ex)
        )


# ===========================================================================
# FIND MISSING TYPES
# ===========================================================================

missing = []


for code, mapping in TYPE_MAP.items():

    fname, tname = mapping

    if (
        fname,
        tname
    ) not in symbol_lookup:

        missing.append(
            "  {} → {} / {}".format(
                code,
                fname,
                tname
            )
        )


# ===========================================================================
# FIND LEVEL
# ===========================================================================

all_levels = list(
    FilteredElementCollector(doc)
    .OfClass(Level)
)


level_map = {}


for lv in all_levels:

    try:

        if lv.Name:

            level_map[
                str(lv.Name)
            ] = lv

    except Exception:
        pass


target_level = level_map.get(
    LEVEL_NAME
)


if target_level is None:

    for name, lv in level_map.items():

        if (
            name.strip().lower()
            ==
            LEVEL_NAME.strip().lower()
        ):

            target_level = lv

            break


if target_level is None:

    raise Exception(
        "Level '{}' not found.\n\n"
        "Available levels:\n{}".format(
            LEVEL_NAME,
            "\n".join(
                "  " + n
                for n in sorted(
                    level_map.keys()
                )
            )
        )
    )


# ===========================================================================
# FIND EXISTING CONDITIONS VIEW
# Never Proposed / overlay. Prefer 1.0 EXISTING CONDITIONS - GROUND.
# ===========================================================================

all_views = list(
    FilteredElementCollector(doc)
    .OfClass(ViewPlan)
)


def _view_scope(name):
    text = str(name or "").lower()
    if "propos" in text or "selling floor" in text:
        return "proposed"
    if "overlay" in text:
        return "overlay"
    if "existing" in text and "condition" in text:
        return "existing"
    return "other"


target_view = None
preferred_view = VIEW_NAME.strip().lower()

for v in all_views:
    try:
        name = str(v.Name)
        if preferred_view and name.strip().lower() == preferred_view:
            if _view_scope(name) != "existing":
                continue
            target_view = v
            break
    except Exception:
        pass

if target_view is None:
    for v in all_views:
        try:
            name = str(v.Name)
            if _view_scope(name) != "existing":
                continue
            if "ground" in name.lower() or "1.0" in name or "1-0" in name:
                target_view = v
                break
        except Exception:
            pass

if target_view is None:
    for v in all_views:
        try:
            if _view_scope(v.Name) == "existing":
                target_view = v
                break
        except Exception:
            pass


# ===========================================================================
# USE VIEW LEVEL IF DIFFERENT
# ===========================================================================

level_override_info = ""


if target_view is not None:

    try:

        view_level = target_view.GenLevel

        if (
            view_level is not None
            and view_level.Id
            != target_level.Id
        ):

            level_override_info = (
                "View '{}' uses level '{}'."
            ).format(
                target_view.Name,
                view_level.Name
            )

            target_level = view_level

    except Exception:
        pass


# ===========================================================================
# BLUE GRAPHICS
# ===========================================================================

BLUE = Color(
    0,
    102,
    204
)


color_override = OverrideGraphicSettings()


try:

    color_override.SetProjectionLineColor(
        BLUE
    )

except Exception:
    pass


try:

    color_override.SetSurfaceForegroundPatternColor(
        BLUE
    )

    color_override.SetSurfaceForegroundPatternVisible(
        True
    )

except Exception:
    pass


# ===========================================================================
# EXISTING PHASE
# ===========================================================================

all_phases = list(
    FilteredElementCollector(doc)
    .OfClass(Phase)
)


existing_phase = None


for ph in all_phases:

    try:

        name = str(
            ph.Name
        ).lower()

        if name in (
            "existing",
            "existing construction",
            "as-built"
        ):

            existing_phase = ph

            break

    except Exception:
        pass


if (
    existing_phase is None
    and all_phases
):

    existing_phase = all_phases[0]


phase_info = (
    existing_phase.Name
    if existing_phase
    else "not set"
)


# ===========================================================================
# TRANSACTION
# ===========================================================================

t = Transaction(
    doc,
    "Place Existing Conditions Gondolas"
)

t.Start()


# ===========================================================================
# DELETE PREVIOUSLY MANAGED GONDOLAS
# ===========================================================================

MANAGED_FAMILIES = {
    "Floor_Gondola",
    "Floor_Gondola_High_Bay",
    "Floor_Gondola_High_Bay-Half_Bay",
    "Wall_Gondola",
    "Wall_Gondola_High_Bay",
    "End_Panel_Decks",
    "Decks_&_Hopper",
    "End_Panel",
    "Floor_Gondola_Queuing"
}


deleted_count = 0


all_instances = list(
    FilteredElementCollector(doc)
    .OfClass(FamilyInstance)
    .ToElements()
)


for inst in all_instances:

    try:

        family_name = (
            get_instance_family_name(inst)
        )

        if (
            family_name
            not in MANAGED_FAMILIES
        ):

            continue


        # ---------------------------------------------------------------
        # LEVEL CHECK
        # ---------------------------------------------------------------

        lv_param = None

        try:

            lv_param = inst.get_Parameter(
                BuiltInParameter.FAMILY_LEVEL_PARAM
            )

        except Exception:
            pass


        if lv_param is None:

            try:

                lv_param = inst.get_Parameter(
                    BuiltInParameter.INSTANCE_REFERENCE_LEVEL_PARAM
                )

            except Exception:
                pass


        if lv_param is not None:

            try:

                if (
                    lv_param.AsElementId()
                    != target_level.Id
                ):

                    continue

            except Exception:
                continue


        # ---------------------------------------------------------------
        # PHASE CHECK
        # ---------------------------------------------------------------

        if existing_phase is not None:

            try:

                ph_param = inst.get_Parameter(
                    BuiltInParameter.PHASE_CREATED
                )

                if ph_param is not None:

                    if (
                        ph_param.AsElementId()
                        != existing_phase.Id
                    ):

                        continue

            except Exception:
                pass


        doc.Delete(
            inst.Id
        )

        deleted_count += 1


    except Exception:
        pass


doc.Regenerate()


# ===========================================================================
# ACTIVATE SYMBOLS
# ===========================================================================

activated = set()


for code, mapping in TYPE_MAP.items():

    fname, tname = mapping

    key = (
        fname,
        tname
    )

    if key not in symbol_lookup:
        continue

    try:

        symbol = symbol_lookup[key]

        if (
            not symbol.IsActive
            and key not in activated
        ):

            symbol.Activate()

            activated.add(key)

    except Exception:
        pass


doc.Regenerate()


# ===========================================================================
# PLACE GONDOLAS
# ===========================================================================

placed = []
skipped = []
wall_placed = []
orientation_report = []


for g in gondolas:

    try:

        # ---------------------------------------------------------------
        # CODE
        # ---------------------------------------------------------------

        code = str(
            g.get(
                "code",
                ""
            )
        ).upper().strip()


        if code not in TYPE_MAP:

            skipped.append(
                "UNKNOWN CODE: {}".format(
                    code
                )
            )

            continue


        # ---------------------------------------------------------------
        # FAMILY / TYPE
        # ---------------------------------------------------------------

        fname, tname = TYPE_MAP[code]

        key = (
            fname,
            tname
        )


        if key not in symbol_lookup:

            skipped.append(
                "MISSING TYPE: {} → {} / {}".format(
                    code,
                    fname,
                    tname
                )
            )

            continue


        symbol = symbol_lookup[key]


        # ---------------------------------------------------------------
        # JSON COORDINATES
        # ---------------------------------------------------------------

        x_mm = float(
            g.get(
                "x",
                0
            )
        )

        y_mm = float(
            g.get(
                "y",
                0
            )
        )


        # ---------------------------------------------------------------
        # CONVERT TO FEET
        # ---------------------------------------------------------------

        x_local_ft = (
            x_mm * MM_TO_FT
        )

        y_local_ft = (
            y_mm * MM_TO_FT
        )


        # ---------------------------------------------------------------
        # APPLY CAD TRANSFORM
        # ---------------------------------------------------------------

        if APPLY_CAD_ROTATION:

            cos_a = math.cos(
                cad_rotation_rad
            )

            sin_a = math.sin(
                cad_rotation_rad
            )

            x_rot = (
                x_local_ft * cos_a
                -
                y_local_ft * sin_a
            )

            y_rot = (
                x_local_ft * sin_a
                +
                y_local_ft * cos_a
            )

        else:

            x_rot = x_local_ft
            y_rot = y_local_ft


        if APPLY_CAD_TRANSLATION:

            x_ft = (
                x_rot
                + cad_offset_x
            )

            y_ft = (
                y_rot
                + cad_offset_y
            )

        else:

            x_ft = x_rot
            y_ft = y_rot


        z_ft = target_level.Elevation


        point = XYZ(
            x_ft,
            y_ft,
            z_ft
        )


        # ---------------------------------------------------------------
        # PLACE FAMILY
        # ---------------------------------------------------------------

        instance = doc.Create.NewFamilyInstance(
            point,
            symbol,
            target_level,
            StructuralType.NonStructural
        )


        # ---------------------------------------------------------------
        # PHASE
        # ---------------------------------------------------------------

        if existing_phase is not None:

            try:

                p_created = instance.get_Parameter(
                    BuiltInParameter.PHASE_CREATED
                )

                if (
                    p_created is not None
                    and not p_created.IsReadOnly
                ):

                    p_created.Set(
                        existing_phase.Id
                    )

            except Exception:
                pass


        # ---------------------------------------------------------------
        # BLUE OVERRIDE
        # ---------------------------------------------------------------

        if target_view is not None:

            try:

                target_view.SetElementOverrides(
                    instance.Id,
                    color_override
                )

            except Exception:
                pass


        # ---------------------------------------------------------------
        # DETERMINE ACTUAL ORIENTATION
        # ---------------------------------------------------------------

        orientation, angle_deg, angle_source = (
            get_orientation(g)
        )


        # ---------------------------------------------------------------
        # ROTATE ABOUT INSTANCE INSERTION POINT
        # ---------------------------------------------------------------

        if (
            angle_deg is not None
            and abs(angle_deg) > 0.0001
        ):

            angle_rad = math.radians(
                angle_deg
            )

            axis = Line.CreateBound(
                point,
                XYZ(
                    point.X,
                    point.Y,
                    point.Z + 1.0
                )
            )

            ElementTransformUtils.RotateElement(
                doc,
                instance.Id,
                axis,
                angle_rad
            )


        # ---------------------------------------------------------------
        # REPORT
        # ---------------------------------------------------------------

        placed.append(
            "{:<24} "
            "@ ({:>9.0f}, {:>9.0f}) mm "
            "angle={:>8.3f}° "
            "{}".format(
                code,
                x_mm,
                y_mm,
                angle_deg
                if angle_deg is not None
                else 0.0,
                angle_source
            )
        )


        orientation_report.append(
            "{} | orientation={} | angle={:.3f}° | source={}".format(
                code,
                orientation,
                angle_deg
                if angle_deg is not None
                else 0.0,
                angle_source
            )
        )


        # ---------------------------------------------------------------
        # WALL GONDOLAS
        # ---------------------------------------------------------------

        if (
            fname
            in (
                "Wall_Gondola",
                "Wall_Gondola_High_Bay"
            )
        ):

            eid_int = safe_element_id_value(
                instance.Id
            )

            wall_placed.append(
                "{:<24} "
                "@ ({:>9.0f}, {:>9.0f}) mm "
                "angle={:>8.3f}° "
                "id={}".format(
                    code,
                    x_mm,
                    y_mm,
                    angle_deg
                    if angle_deg is not None
                    else 0.0,
                    eid_int
                )
            )


    except Exception as ex:

        skipped.append(
            "ERROR {} :: {}".format(
                g.get(
                    "code",
                    "?"
                ),
                str(ex)
            )
        )


# ===========================================================================
# COMMIT
# ===========================================================================

t.Commit()


# ===========================================================================
# REPORT
# ===========================================================================

sep = "=" * 75


lines = [

    "",
    sep,
    " EXISTING CONDITIONS — GONDOLA PLACEMENT",
    sep,
    "",

    "Script version         : {}".format(
        SCRIPT_VERSION
    ),

    "JSON path              : {}".format(
        JSON_PATH
    ),

    "Total JSON items       : {}".format(
        len(gondolas)
    ),

    "Placed                 : {}".format(
        len(placed)
    ),

    "Skipped                : {}".format(
        len(skipped)
    ),

    "Deleted previous       : {}".format(
        deleted_count
    ),

    "",

    "LEVEL",
    "  Level used           : {}".format(
        target_level.Name
    ),

    "  Elevation            : {:.3f} ft".format(
        target_level.Elevation
    ),

    "  Level note           : {}".format(
        level_override_info
        if level_override_info
        else "Matched LEVEL_NAME"
    ),

    "",

    "PHASE",
    "  Phase used           : {}".format(
        phase_info
    ),

    "",

    "CAD TRANSFORM",
    "  {}".format(
        cad_offset_info
    ),

    "",

    "ORIENTATION",
    "  JSON angle enabled   : {}".format(
        USE_JSON_ANGLE
    ),

    "  Angle sign           : {}".format(
        ANGLE_SIGN
    ),

    "  Angle offset         : {:.3f}°".format(
        ANGLE_OFFSET_DEG
    ),

    "  CAD rotation applied : {}".format(
        APPLY_CAD_ROTATION
    ),

    "",

    "ALL CAD IMPORTS:"
]


if all_cad_found:

    lines.extend(
        all_cad_found
    )

else:

    lines.append(
        "    NONE FOUND"
    )


# ===========================================================================
# ORIENTATION REPORT
# ===========================================================================

lines.extend(
    [
        "",
        "ORIENTATION USED FOR EACH ITEM:"
    ]
)


if orientation_report:

    lines.extend(
        [
            "    " + x
            for x in orientation_report
        ]
    )

else:

    lines.append(
        "    NONE"
    )


# ===========================================================================
# WALL GONDOLAS
# ===========================================================================

if wall_placed:

    lines.extend(
        [
            "",
            "WALL GONDOLAS PLACED: {}".format(
                len(wall_placed)
            )
        ]
    )

    lines.extend(
        [
            "    " + x
            for x in wall_placed
        ]
    )


# ===========================================================================
# MISSING TYPES
# ===========================================================================

if missing:

    lines.extend(
        [
            "",
            "MISSING REVIT TYPES:"
        ]
    )

    lines.extend(
        [
            "    " + x
            for x in missing
        ]
    )


# ===========================================================================
# SYMBOL ERRORS
# ===========================================================================

if symbol_errors:

    lines.extend(
        [
            "",
            "SYMBOL LOOKUP WARNINGS:"
        ]
    )

    lines.extend(
        [
            "    " + x
            for x in symbol_errors
        ]
    )


# ===========================================================================
# SKIPPED
# ===========================================================================

if skipped:

    lines.extend(
        [
            "",
            "SKIPPED / ERRORS:"
        ]
    )

    lines.extend(
        [
            "    " + x
            for x in skipped
        ]
    )


# ===========================================================================
# PLACED
# ===========================================================================

lines.extend(
    [
        "",
        "PLACED GONDOLAS:"
    ]
)


lines.extend(
    [
        "    " + x
        for x in placed
    ]
)


lines.extend(
    [
        "",
        sep,
        ""
    ]
)


# ===========================================================================
# DYNAMO OUTPUT
# ===========================================================================

OUT = "\n".join(
    lines
)