# Dynamo_ExistingGondolaPlacement
# Revit 2025 / Dynamo CPython3 compatible
#
# Places existing-condition gondolas from the JSON generated by
# Gondola_OrientationDetector.py.
#
# Tracing / rotation notes
# ------------------------
# Use placement_angle / orientation_angle from JSON. Do NOT use the DXF
# TEXT rotation field — that is the glyph baseline, not the bay axis.
# Coordinates are mapped through the selected CAD import transform
# (origin, rotation, and scale) so the family lands on the linked plan.

import clr
import os
import json
import math
import re


# ===========================================================================
# REVIT REFERENCES
# ===========================================================================

clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import (
    FilteredElementCollector,
    FamilySymbol,
    FamilyInstance,
    Transaction,
    XYZ,
    Level,
    ViewPlan,
    Line,
    ElementTransformUtils,
    Phase,
    BuiltInParameter,
    OverrideGraphicSettings,
    Color,
    ImportInstance,
    ElementId
)

from Autodesk.Revit.DB.Structure import StructuralType
from RevitServices.Persistence import DocumentManager


# ===========================================================================
# SETTINGS
# ===========================================================================

JSON_PATH = r"C:\Users\msharan\OneDrive - Kmart Australia Limited\Desktop\Stores Foundry\Tracing\json\gondola_data_Marrickville_New2.json"

# Host ONLY on Existing Conditions Ground. Opening that view is not
# enough — instances from the last run are still on 2.0 PROPOSED.
USE_ACTIVE_PLAN_VIEW = True
TARGET_VIEW_NAME = "1.0 EXISTING CONDITIONS - GROUND"
LEVEL_NAME = "1.0 EXISTING CONDITIONS - GROUND"
REFUSE_PROPOSED_HOST = True

# Partial CAD import name. Prefer the existing-conditions link.
CAD_LINK_NAME = "Existing Conditions"

MM_TO_FT = 1.0 / 304.8

# Use traced bay axis from JSON (placement_angle / orientation_angle).
USE_JSON_ANGLE = True

# JSON degrees are CCW from CAD +X. Flip if a family is mirrored.
ANGLE_SIGN = 1.0

# Extra constant offset (degrees) applied after CAD rotation.
ANGLE_OFFSET_DEG = 0.0

VERTICAL_FALLBACK_DEG = 0.0
HORIZONTAL_FALLBACK_DEG = 90.0

# Map JSON millimetres through the CAD import transform (origin + rotation + scale).
APPLY_CAD_TRANSFORM = True

# Per-family extra rotation if a family origin is modelled 90° off the CAD axis.
FAMILY_ANGLE_OFFSET = {
    "Floor_Gondola": 0.0,
    "Floor_Gondola_High_Bay": 0.0,
    "Floor_Gondola_High_Bay-Half_Bay": 0.0,
    "Wall_Gondola": 0.0,
    "Wall_Gondola_High_Bay": 0.0,
    "End_Panel": 0.0,
    "End_Panel_Decks": 0.0,
    "Decks_&_Hopper": 0.0,
    "Floor_Gondola_Queuing": 0.0,
    "Hotspots": 0.0,
}


TYPE_MAP = {

    # 15F Standard
    "15FLCA": ("Floor_Gondola", "15FLCA"),
    "15FLCS": ("Floor_Gondola", "15FLCS"),
    "15FLOA": ("Floor_Gondola", "15FLOA"),
    "15FLOS": ("Floor_Gondola", "15FLOS"),
    "15FMCA": ("Floor_Gondola", "15FMCA"),
    "15FMCS": ("Floor_Gondola", "15FMCS"),
    "15FMOA": ("Floor_Gondola", "15FMOA"),
    "15FMOS": ("Floor_Gondola", "15FMOS"),

    # 18F
    "18FLCA": ("Floor_Gondola", "18FLCA"),
    "18FLCS": ("Floor_Gondola", "18FLCS"),
    "18FMCA": ("Floor_Gondola", "18FMCA"),
    "18FMCS": ("Floor_Gondola", "18FMCS"),
    "18FMOA": ("Floor_Gondola", "18FMOA"),
    "18FMOS": ("Floor_Gondola", "18FMOS"),

    # 21F
    "21FLCA": ("Floor_Gondola", "21FLCA"),
    "21FLCS": ("Floor_Gondola", "21FLCS"),
    "21FLOA": ("Floor_Gondola", "21FLOA"),
    "21FLOS": ("Floor_Gondola", "21FLOS"),
    "21FMCA": ("Floor_Gondola", "21FMCA"),
    "21FMCS": ("Floor_Gondola", "21FMCS"),
    "21FMOA": ("Floor_Gondola", "21FMOA"),
    "21FMOS": ("Floor_Gondola", "21FMOS"),

    # 34F
    "34FLCA": ("Floor_Gondola", "34FLCA"),
    "34FLCS": ("Floor_Gondola", "34FLCS"),
    "34FLOA": ("Floor_Gondola", "34FLOA"),
    "34FLOS": ("Floor_Gondola", "34FLOS"),
    "34FMCA": ("Floor_Gondola", "34FMCA"),
    "34FMCS": ("Floor_Gondola", "34FMCS"),
    "34FMOA": ("Floor_Gondola", "34FMOA"),
    "34FMOS": ("Floor_Gondola", "34FMOS"),

    # 34H
    "34HLCA": ("Floor_Gondola_High_Bay", "34HLCA"),
    "34HLCS": ("Floor_Gondola_High_Bay", "34HLCS"),
    "34HLOA": ("Floor_Gondola_High_Bay", "34HLOA"),
    "34HLOS": ("Floor_Gondola_High_Bay", "34HLOS"),

    # 27H
    "27HLCA": ("Floor_Gondola_High_Bay", "27HLCA"),
    "27HLCS": ("Floor_Gondola_High_Bay", "27HLCS"),

    # 34S
    "34SLCA": ("Floor_Gondola", "34FLCA EXTENSION LEG"),
    "34SLCS": ("Floor_Gondola", "34FLCS"),

    # 34RD
    "34RDLC": ("End_Panel_Decks", "34ELO"),
    "FLATDECK": ("Decks_&_Hopper", "LRD"),
    "FLATDECKWS": ("Decks_&_Hopper", "LRD_2S"),

    # 36W
    "36WLOA": ("Wall_Gondola", "36WLOA"),
    "36WLOS": ("Wall_Gondola", "36WLOS"),
    "36WLCA": ("Wall_Gondola", "36WLCA"),
    "36WLCS": ("Wall_Gondola", "36WLCS"),
    "15WLOS": ("Wall_Gondola", "15WLOS"),

    # 36B
    "36BLOA": ("Floor_Gondola_High_Bay", "36HLOA"),
    "36BLOS": ("Wall_Gondola_High_Bay", "36HLOS"),
    "36BLCA": ("Floor_Gondola_High_Bay", "36HLCA"),
    "36BLCS": ("Wall_Gondola_High_Bay", "36HLCS"),

    # 15W
    "15WLCA": ("Wall_Gondola", "15WLCA"),
    "15WLCS": ("Wall_Gondola", "15WLCS"),
    "15WLOS": ("Wall_Gondola", "15WLOS"),
    "15WMCA": ("Wall_Gondola", "15WMCA"),
    "15WMCS": ("Wall_Gondola", "15WMCS"),

    # 12W
    "12WMCA": ("Wall_Gondola", "12WMCA"),
    "12WMCS": ("Wall_Gondola", "12WMCS"),

    # WA / WS
    "15FMWA": ("Floor_Gondola", "15FMWA"),
    "15FMWS": ("Floor_Gondola", "15FMWS"),
    "21FMWA": ("Floor_Gondola", "21FMWA"),
    "21FMWS": ("Floor_Gondola", "21FMWS"),
    "34FMWA": ("Floor_Gondola", "34FMWA"),
    "34FMWS": ("Floor_Gondola", "34FMWS"),

    # 12F
    "12FLCA": ("Floor_Gondola", "12FLCA"),
    "12FLCS": ("Floor_Gondola", "12FLCS"),
    "12FLOA": ("Floor_Gondola", "12FLOA"),
    "12FLOS": ("Floor_Gondola", "12FLOS"),
    "12FMCA": ("Floor_Gondola", "12FMCA"),
    "12FMCS": ("Floor_Gondola", "12FMCS"),
    "12FMOA": ("Floor_Gondola", "12FMOA"),
    "12FMOS": ("Floor_Gondola", "12FMOS"),

    # 36
    "36HLCA": ("Floor_Gondola_High_Bay", "36HLCA"),
    "36HLCS": ("Floor_Gondola_High_Bay", "36HLCS"),
    "36HLOA": ("Floor_Gondola_High_Bay", "36HLOA"),
    "36HLOS": ("Floor_Gondola_High_Bay", "36HLOS"),

    # 34W
    "34WLOA": ("Wall_Gondola", "34WLOA"),
    "34WLOS": ("Wall_Gondola", "34WLOS"),
    "34WLCA": ("Wall_Gondola", "34WLCA"),
    "34WLCS": ("Wall_Gondola", "34WLCS"),

    # 32W
    "32WLOA": ("Wall_Gondola", "32WLOA"),
    "32WLOS": ("Wall_Gondola", "32WLOS"),
    "32WLCA": ("Wall_Gondola", "32WLCA"),
    "32WLCS": ("Wall_Gondola", "32WLCS"),

    # 30W
    "30WLOA": ("Wall_Gondola", "30WLOA"),
    "30WLOS": ("Wall_Gondola", "30WLOS"),
    "30WLCA": ("Wall_Gondola", "30WLCA"),
    "30WLCS": ("Wall_Gondola", "30WLCS"),

    # 27W
    "27WLOA": ("Wall_Gondola", "27WLOA"),
    "27WLOS": ("Wall_Gondola", "27WLOS"),
    "27WLCA": ("Wall_Gondola", "27WLCA"),
    "27WLCS": ("Wall_Gondola", "27WLCS"),

    # 21W
    "21WLOA": ("Wall_Gondola", "21WLOA"),
    "21WLOS": ("Wall_Gondola", "21WLOS"),
    "21WLCA": ("Wall_Gondola", "21WLCA"),
    "21WLCS": ("Wall_Gondola", "21WLCS"),

    # END PANELS
    "12DELC": ("End_Panel", "12DELC"),
    "12DEMO": ("End_Panel", "12DEMO"),
    "12ELC": ("End_Panel", "12ELC"),
    "12ELO": ("End_Panel", "12ELO"),
    "12EMC": ("End_Panel", "12EMC"),
    "12EMO": ("End_Panel", "12EMO"),
    "12SELC": ("End_Panel", "12SELC"),
    "12SEMC": ("End_Panel", "12SEMC"),

    "15DELC": ("End_Panel", "15DELC"),
    "15DELO": ("End_Panel", "15DELO"),
    "15DEMC": ("End_Panel", "15DEMC"),
    "15DEMO": ("End_Panel", "15DEMO"),
    "15ELC": ("End_Panel", "15ELC"),
    "15ELO": ("End_Panel", "15ELO"),
    "15ELW": ("End_Panel", "15ELW"),
    "15EMC": ("End_Panel", "15EMC"),
    "15EMM": ("End_Panel", "15EMM"),
    "15EMO": ("End_Panel", "15EMO"),
    "15EMW": ("End_Panel", "15EMW"),
    "15SELC": ("End_Panel", "15SELC"),
    "15SELO": ("End_Panel", "15SELO"),
    "15SEMC": ("End_Panel", "15SEMC"),
    "15SEMO": ("End_Panel", "15SEMO"),
    "15SEMW": ("End_Panel", "15SEMW"),

    "18DELC": ("End_Panel", "18DELC"),
    "18DEMO": ("End_Panel", "18DEMO"),
    "18DEMC": ("End_Panel", "18DEMC"),
    "18ELC": ("End_Panel", "18ELC"),
    "18ELM": ("End_Panel", "18ELM"),
    "18ELO": ("End_Panel", "18ELO"),
    "18EMC": ("End_Panel", "18EMC"),
    "18EMM": ("End_Panel", "18EMM"),
    "18EMO": ("End_Panel", "18EMO"),
    "18POSTER END": ("End_Panel", "18POSTER END"),
    "18SELC": ("End_Panel", "18SELC"),
    "18SELO": ("End_Panel", "18SELO"),
    "18SEMC": ("End_Panel", "18SEMC"),
    "18SEMO": ("End_Panel", "18SEMO"),

    "21DELC": ("End_Panel", "21DELC"),
    "21DELC 200 PEG": ("End_Panel", "21DELC 200 PEG"),
    "21DELM": ("End_Panel", "21DELM"),
    "21DELO": ("End_Panel", "21DELO"),
    "21DEMC": ("End_Panel", "21DEMC"),
    "21DEMO": ("End_Panel", "21DEMO"),
    "21ELC": ("End_Panel", "21ELC"),
    "21ELM": ("End_Panel", "21ELM"),
    "21ELO": ("End_Panel", "21ELO"),
    "21ELW": ("End_Panel", "21ELW"),
    "21ELWM": ("End_Panel", "21ELWM"),
    "21EMC": ("End_Panel", "21EMC"),
    "21EMM": ("End_Panel", "21EMM"),
    "21EMO": ("End_Panel", "21EMO"),
    "21EMW": ("End_Panel", "21EMW"),
    "21EMWM": ("End_Panel", "21EMWM"),
    "21POSTER END": ("End_Panel", "21POSTER END"),
    "21SELC": ("End_Panel", "21SELC"),
    "21SELO": ("End_Panel", "21SELO"),
    "21SELW": ("End_Panel", "21SELW"),
    "21SEMC": ("End_Panel", "21SEMC"),
    "21SEMO": ("End_Panel", "21SEMO"),
    "21SEMW": ("End_Panel", "21SEMW"),

    "26DELW - DIVIDING WALL - END": (
        "End_Panel",
        "26DELW - DIVIDING WALL - END"
    ),

    "26EMW - DIVIDING WALL EPF": (
        "End_Panel",
        "26EMW - DIVIDING WALL EPF"
    ),

    "27ELC": ("End_Panel", "27ELC"),
    "27ELO": ("End_Panel", "27ELO"),
    "27ELW": ("End_Panel", "27ELW"),
    "27EMC": ("End_Panel", "27EMC"),
    "27EMO": ("End_Panel", "27EMO"),
    "27POSTER 540 END": ("End_Panel", "27POSTER 540 END"),
    "27SELC": ("End_Panel", "27SELC"),
    "27SELO": ("End_Panel", "27SELO"),
    "27SELW": ("End_Panel", "27SELW"),

    "30DELO": ("End_Panel", "30DELO"),
    "30DEMC": ("End_Panel", "30DEMC"),
    "30DEMO": ("End_Panel", "30DEMO"),
    "30ELC": ("End_Panel", "30ELC"),
    "30ELM": ("End_Panel", "30ELM"),
    "30ELO": ("End_Panel", "30ELO"),
    "30EMC": ("End_Panel", "30EMC"),
    "30EMM": ("End_Panel", "30EMM"),
    "30EMO": ("End_Panel", "30EMO"),
    "30SELC": ("End_Panel", "30SELC"),
    "30SELO": ("End_Panel", "30SELO"),
    "30SELW": ("End_Panel", "30SELW"),
    "30SEMC": ("End_Panel", "30SEMC"),
    "30SEMO": ("End_Panel", "30SEMO"),

    "32DELC": ("End_Panel", "32DELC"),
    "32DELO": ("End_Panel", "32DELO"),
    "32DEMC": ("End_Panel", "32DEMC"),
    "32DEMO": ("End_Panel", "32DEMO"),
    "32ELC": ("End_Panel", "32ELC"),
    "32ELM": ("End_Panel", "32ELM"),
    "32ELO": ("End_Panel", "32ELO"),
    "32ELW": ("End_Panel", "32ELW"),
    "32ELWM": ("End_Panel", "32ELWM"),
    "32EMC": ("End_Panel", "32EMC"),
    "32EMM": ("End_Panel", "32EMM"),
    "32EMO": ("End_Panel", "32EMO"),
    "32EMW": ("End_Panel", "32EMW"),
    "32EMWM": ("End_Panel", "32EMWM"),
    "32SELC": ("End_Panel", "32SELC"),
    "32SELO": ("End_Panel", "32SELO"),
    "32SELW": ("End_Panel", "32SELW"),
    "32SEMC": ("End_Panel", "32SEMC"),
    "32SEMO": ("End_Panel", "32SEMO"),
    "32SEMW": ("End_Panel", "32SEMW"),

    "34DELC": ("End_Panel", "34DELC"),
    "34DELO": ("End_Panel", "34DELO"),
    "34DEMC": ("End_Panel", "34DEMC"),
    "34DEMO": ("End_Panel", "34DEMO"),
    "34ELC": ("End_Panel", "34ELC"),
    "34ELM": ("End_Panel", "34ELM"),
    "34ELO": ("End_Panel", "34ELO"),
    "34ELW": ("End_Panel", "34ELW"),
    "34ELWM": ("End_Panel", "34ELWM"),
    "34EMC": ("End_Panel", "34EMC"),
    "34EMM": ("End_Panel", "34EMM"),
    "34EMO": ("End_Panel", "34EMO"),
    "34EMW": ("End_Panel", "34EMW"),
    "34EMWM": ("End_Panel", "34EMWM"),
    "34SELC": ("End_Panel", "34SELC"),
    "34SELO": ("End_Panel", "34SELO"),
    "34SELW": ("End_Panel", "34SELW"),
    "34SEMC": ("End_Panel", "34SEMC"),
    "34SEMO": ("End_Panel", "34SEMO"),
    "34SEMW": ("End_Panel", "34SEMW"),
    "34SELW 540 END": ("End_Panel", "34SELW 540 END"),
    "34SEMV 540 END": ("End_Panel", "34SEMV 540 END"),

    "HALLMARK END 1200": ("End_Panel", "HALLMARK END 1200"),
    "HALLMARK END 900": ("End_Panel", "HALLMARK END 900"),

    "12QMCA": ("Floor_Gondola_Queuing", "12QMCA"),
    "12QMCS": ("Floor_Gondola_Queuing", "12QMCS"),

    #OLD VS new Codes
    "15EPLC": ("End_Panel", "15ELC"),
"15EPMC": ("End_Panel", "15EMC"),
"15EPMO": ("End_Panel", "15EMO"),
"15EPLO": ("End_Panel", "15ELO"),
"15EPMM": ("End_Panel", "15EMM"),

"15SHMC": ("End_Panel", "15SEMC"),
"15SHLC": ("End_Panel", "15SELC"),
"15SHLO": ("End_Panel", "15SELO"),

"18EPLC": ("End_Panel", "18ELC"),
"18EPMC": ("End_Panel", "18EMC"),
"18EPMO": ("End_Panel", "18EMO"),
"18EPLO": ("End_Panel", "18ELO"),
"18EPMM": ("End_Panel", "18EMM"),

"18SHMC": ("End_Panel", "18SEMC"),
"18SHLC": ("End_Panel", "18SELC"),
"18SHLO": ("End_Panel", "18SELO"),

"21EPLC": ("End_Panel", "21ELC"),
"21EPMC": ("End_Panel", "21EMC"),
"21EPMO": ("End_Panel", "21EMO"),
"21EPLO": ("End_Panel", "21ELO"),
"21EPMM": ("End_Panel", "21EMM"),
"21SHMC": ("End_Panel", "21SEMC"),
"21SHLC": ("End_Panel", "21SELC"),
"21SHLO": ("End_Panel", "21SELO"),

"27HLO": ("End_Panel", "27SELOS"),

"32EPLC": ("End_Panel", "32EMC"),
"32EPMC": ("End_Panel", "32EMC"),
"32EPMO": ("End_Panel", "32EMO"),
"32EPLO": ("End_Panel", "32ELO"),
"32SHLO": ("End_Panel", "32SELO"),

"34EPLC": ("End_Panel", "34EMC"),
"34EPMC": ("End_Panel", "34EMC"),
"34EPMO": ("End_Panel", "34EMO"),
"34EPLO": ("End_Panel", "34ELO"),
"34SHLO": ("End_Panel", "34SELO"),


"34BLOA": ("Wall_Gondola_High_Bay", "34HLCA OUTRIGGER POST ADDED"),
"34BLOS": ("Wall_Gondola_High_Bay", "34HLCS"),

"36BLOA": ("Wall_Gondola_High_Bay", "36HLCA OUTRIGGER POST ADDED"),
"36BLOS": ("Wall_Gondola_High_Bay", "36HLCS"),

"15RDLC":("End_Panel_Decks","15ELC (End_Panel_Decks)"),
"15RDLO":("End_Panel_Decks","15ELO (End_Panel_Decks)"),
"15RDMC":("End_Panel_Decks","15EMC(End_Panel_Decks)"),
"15RDMO":("End_Panel_Decks","15EMO(End_Panel_Decks)"),

"18RDLC":("End_Panel_Decks","18ELC(End_Panel_Decks)"),
"18RDLO":("End_Panel_Decks","18ELO(End_Panel_Decks)"),
"18RDMC":("End_Panel_Decks","18EMC(End_Panel_Decks)"),
"18RDMO":("End_Panel_Decks","18EMO(End_Panel_Decks)"),

"21RDLC":("End_Panel_Decks","21ELC(End_Panel_Decks)"),
"21RDLO":("End_Panel_Decks","21ELO(End_Panel_Decks)"),
"21RDMC":("End_Panel_Decks","21EMC(End_Panel_Decks)"),
"21RDMO":("End_Panel_Decks","21EMO(End_Panel_Decks)"),

"32RDLC":("End_Panel_Decks","32ELC(End_Panel_Decks)"),
"32RDLO":("End_Panel_Decks","32ELO(End_Panel_Decks)"),
"32RDMC":("End_Panel_Decks","32EMC(End_Panel_Decks)"),
"32RDMO":("End_Panel_Decks","32EMO(End_Panel_Decks)"),

"34RDLC":("End_Panel_Decks","34ELC(End_Panel_Decks)"),
"34RDLO":("End_Panel_Decks","34ELO(End_Panel_Decks)"),
"34RDMC":("End_Panel_Decks","34EMC(End_Panel_Decks)"),
"34RDMO":("End_Panel_Decks","34EMO(End_Panel_Decks)"),
"34RELO":("End_Panel_Decks","34ELO(End_Panel_Decks)"),

"FLATDECK W/-SURROUND":("Decks_&_Hopper","LRD_2S"),
"FLATDECK":("Decks_&_Hopper","LRD_2"),
"DECK TABLE":("Decks_&_Hopper","Deck_Table"),
"HOPPER UNIT 2150H":("Decks_&_Hopper","HOP21"),


"HOT SPOT 1500H":("Hotspots","15H Hotspot"),
"HOT SPOT COOKBOOKS":("Hotspots","15H Cookbook"),
"HOT SPOT 2100H":("Hotspots","21H Hotspot"),
"HOT SPOT 3000H":("Hotspots","30H Hotspot"),
"HOT SPOT 3200H":("Hotspots","32H Hotspot"),
"HOT SPOT 3400H":("Hotspots","34H Hotspot"),

"Straight rail":("Hotspots","racking-straight rail"),

"6Way":("Hotspots","Racking-6_Way"),
"16_Way":("Hotspots","Racking-16_Way"),

"T2 TABLE":("Hotspots","T2 VM RAIL + DISPLAY ARM (TABLE_T)"),
"T2 ARM ONLY":("Hotspots","T2 TABLE ARM ONLY"),

"HANGER TOTEM":("Hotspots","HANGER (Bin_240L)"),

}

TYPE_MAP = {
    " ".join(str(key).upper().split()): value
    for key, value in TYPE_MAP.items()
}

# Extra (family, type) tries when the mapped name is not loaded in the project.
TYPE_ALIASES = {
    "6WAY": [
        ("Hotspots", "Racking-6_Way"),
        ("Hotspots", "Racking-6 Way"),
        ("Hotspots", "Racking - 6 Way"),
        ("Hotspots", "6_Way"),
        ("Hotspots", "6Way"),
        ("Hotspots", "6 Way"),
        ("Hotspots", "6-Way"),
        ("Hotspots", "Racking-6Way"),
    ],
    "T2 ARM ONLY": [
        ("Hotspots", "T2 TABLE ARM ONLY"),
        ("Hotspots", "T2 ARM ONLY"),
        ("Hotspots", "T2 ARM"),
        ("Hotspots", "T2 TABLE ARM"),
        ("Hotspots", "T2 VM RAIL + DISPLAY ARM (TABLE_T)"),
    ],
    "34RELO": [
        ("End_Panel", "34ELO"),
        ("End_Panel_Decks", "34ELO"),
        ("End_Panel_Decks", "34ELO(End_Panel_Decks)"),
        ("End_Panel_Decks", "34ELO (End_Panel_Decks)"),
    ],
    "16_WAY": [
        ("Hotspots", "Racking-16_Way"),
        ("Hotspots", "Racking-16 Way"),
        ("Hotspots", "16_Way"),
        ("Hotspots", "16 Way"),
        ("Hotspots", "16-Way"),
    ],
    "STRAIGHT RAIL": [
        ("Hotspots", "racking-straight rail"),
        ("Hotspots", "Straight rail"),
        ("Hotspots", "Racking-Straight Rail"),
        ("Hotspots", "Straight Rail"),
    ],
}


# ===========================================================================
# SAFE REVIT HELPERS
# ===========================================================================

def safe_element_name(element):
    if element is None:
        return ""
    try:
        value = element.Name
        if value:
            return str(value)
    except Exception:
        pass
    try:
        p = element.get_Parameter(BuiltInParameter.SYMBOL_NAME_PARAM)
        if p is not None:
            value = p.AsString()
            if value:
                return value
    except Exception:
        pass
    return ""


def safe_family_name(symbol):
    if symbol is None:
        return ""
    try:
        value = symbol.FamilyName
        if value:
            return str(value)
    except Exception:
        pass
    try:
        family = symbol.Family
        if family is not None:
            value = family.Name
            if value:
                return str(value)
    except Exception:
        pass
    return ""


def safe_symbol_name(symbol):
    if symbol is None:
        return ""
    try:
        value = symbol.Name
        if value:
            return str(value)
    except Exception:
        pass
    try:
        p = symbol.get_Parameter(BuiltInParameter.SYMBOL_NAME_PARAM)
        if p is not None:
            value = p.AsString()
            if value:
                return value
    except Exception:
        pass
    return ""


def safe_element_id_value(element_id):
    if element_id is None:
        return None
    try:
        return int(element_id.Value)
    except Exception:
        pass
    try:
        return int(element_id.IntegerValue)
    except Exception:
        pass
    try:
        return int(str(element_id))
    except Exception:
        return None


def get_instance_family_name(instance):
    if instance is None:
        return ""
    try:
        return safe_family_name(instance.Symbol)
    except Exception:
        return ""


def normalize_code(text):
    if text is None:
        return ""
    raw = str(text).replace("\\P", " ")
    raw = re.sub(r"\s+", " ", raw)
    return raw.upper().strip()


def name_key(value):
    return re.sub(r"[^A-Z0-9]", "", str(value or "").upper())


def name_tokens(value):
    return re.findall(r"[A-Z0-9]+", str(value or "").upper())


def score_symbol_candidate(code, family_hint, type_hint, family_name, type_name):
    code_k = name_key(code)
    hint_k = name_key(type_hint)
    fam_k = name_key(family_name)
    typ_k = name_key(type_name)
    hint_fam = name_key(family_hint)
    score = 0
    if hint_k and typ_k == hint_k:
        score += 120
    if code_k and typ_k == code_k:
        score += 110
    if hint_k and (hint_k in typ_k or typ_k in hint_k):
        score += 70
    if code_k and code_k in typ_k:
        score += 60
    if hint_fam and fam_k == hint_fam:
        score += 40
    elif hint_fam and (hint_fam in fam_k or fam_k in hint_fam):
        score += 20
    code_tokens = set(name_tokens(code))
    hint_tokens = set(name_tokens(type_hint))
    type_tokens = set(name_tokens(type_name))
    ignore = {"THE", "AND", "END", "PANEL", "GONDOLA", "FAMILY"}
    if code_tokens and type_tokens:
        overlap = (code_tokens & type_tokens) - ignore
        score += 8 * len(overlap)
        extra = type_tokens - code_tokens - hint_tokens - ignore
        score -= 6 * len(extra)
        if "T2" in code_tokens and "T2" in type_tokens and "ARM" in type_tokens:
            score += 50
            if "ONLY" in code_tokens and "TABLE" in type_tokens and "ARM" in type_tokens:
                score -= 35
        if "6WAY" in code_k and "6WAY" in typ_k:
            score += 80
        if "6" in code_tokens and "WAY" in type_tokens:
            score += 40
        if "16" in code_tokens and "WAY" in type_tokens:
            score += 40
    return score


def normalize_angle(angle):
    try:
        angle = float(angle)
    except Exception:
        return None
    angle = angle % 360.0
    if angle < 0:
        angle += 360.0
    return angle


def get_json_angle(g):
    """
    Prefer the traced gondola axis. Never consume DXF TEXT 'rotation'.
    """
    for key in (
        "placement_angle",
        "orientation_angle",
        "geometry_angle",
        "axis_angle",
        "angle",
        "angle_deg",
    ):
        value = g.get(key, None)
        if value is None or value == "":
            continue
        try:
            return normalize_angle(float(value) * ANGLE_SIGN + ANGLE_OFFSET_DEG)
        except Exception:
            pass
    return None


def get_orientation(g, cad_rotation_deg, family_name):
    orientation = str(g.get("orientation", "") or "").upper().strip()
    json_angle = get_json_angle(g) if USE_JSON_ANGLE else None
    source = "fallback"

    if json_angle is not None:
        angle = json_angle
        source = "JSON placement/orientation angle"
        if not orientation:
            orientation = "ANGLE"
    elif orientation == "HORIZONTAL":
        angle = normalize_angle(HORIZONTAL_FALLBACK_DEG)
        source = "fallback horizontal"
    elif orientation == "VERTICAL":
        angle = normalize_angle(VERTICAL_FALLBACK_DEG)
        source = "fallback vertical"
    else:
        angle = normalize_angle(VERTICAL_FALLBACK_DEG)
        source = "fallback"

    if APPLY_CAD_TRANSFORM:
        angle = normalize_angle(angle + cad_rotation_deg)
        source = source + " + CAD rotation"

    extra = FAMILY_ANGLE_OFFSET.get(family_name, 0.0) or 0.0
    if extra:
        angle = normalize_angle(angle + extra)
        source = source + " + family offset"

    return orientation, angle, source


def instance_origin(instance, fallback):
    try:
        loc = instance.Location
        pt = loc.Point
        if pt is not None:
            return pt
    except Exception:
        pass
    return fallback


# ===========================================================================
# READ JSON
# ===========================================================================

if not os.path.isfile(JSON_PATH):
    OUT = "JSON NOT FOUND:\n\n{}".format(JSON_PATH)
    raise FileNotFoundError(OUT)

with open(JSON_PATH, "r") as f:
    data = json.load(f)

gondolas = data.get("gondolas", [])


# ===========================================================================
# CONNECT TO REVIT
# ===========================================================================

doc = DocumentManager.Instance.CurrentDBDocument
if doc is None:
    raise Exception("Could not obtain current Revit document.")

uidoc = None
try:
    uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
except Exception:
    uidoc = None


# ===========================================================================
# FIND CAD IMPORT
# ===========================================================================

cad_offset_x = 0.0
cad_offset_y = 0.0
cad_rotation_rad = 0.0
cad_basis_xx = 1.0
cad_basis_xy = 0.0
cad_basis_yx = 0.0
cad_basis_yy = 1.0
cad_transform = None

cad_offset_info = "No CAD transform found. Using origin (0,0)."
all_cad_found = []
all_imports = list(FilteredElementCollector(doc).OfClass(ImportInstance))
selected_import = None
cad_candidates = []

for imp in all_imports:
    try:
        sym = doc.GetElement(imp.GetTypeId())
        cad_name_str = ""
        try:
            p = sym.get_Parameter(BuiltInParameter.IMPORT_SYMBOL_NAME)
            if p is not None:
                cad_name_str = p.AsString() or ""
        except Exception:
            pass
        if not cad_name_str:
            cad_name_str = safe_element_name(sym)
        if not cad_name_str:
            continue

        transform = imp.GetTotalTransform()
        origin = transform.Origin
        ox = origin.X
        oy = origin.Y
        bx = transform.BasisX
        by = transform.BasisY
        cad_angle = math.atan2(bx.Y, bx.X)

        try:
            link_type = "Link" if imp.IsLinked else "Import"
        except Exception:
            link_type = "Import"

        all_cad_found.append(
            "    [{}] {} | offset=({:.0f},{:.0f}) mm | rotation={:.3f}° | "
            "|X|={:.4f} |Y|={:.4f}".format(
                link_type,
                cad_name_str,
                ox * 304.8,
                oy * 304.8,
                math.degrees(cad_angle),
                bx.GetLength(),
                by.GetLength(),
            )
        )

        low = cad_name_str.lower()
        if CAD_LINK_NAME and CAD_LINK_NAME.lower() not in low:
            continue

        score = 0
        if "existing" in low:
            score += 20
        if "condition" in low:
            score += 15
        if "selling" in low:
            score -= 10
        cad_candidates.append((score, imp, transform, ox, oy, cad_angle, bx, by, link_type, cad_name_str))
    except Exception as ex:
        all_cad_found.append("    CAD ERROR: {}".format(str(ex)))

if cad_candidates:
    cad_candidates.sort(key=lambda row: row[0], reverse=True)
    score, selected_import, cad_transform, cad_offset_x, cad_offset_y, cad_rotation_rad, bx, by, link_type, cad_name_str = cad_candidates[0]
    cad_basis_xx = bx.X
    cad_basis_xy = bx.Y
    cad_basis_yx = by.X
    cad_basis_yy = by.Y
    cad_offset_info = (
        "[{}] {} | offset=({:.3f},{:.3f}) ft = ({:.0f},{:.0f}) mm | "
        "rotation={:.3f}°"
    ).format(
        link_type,
        cad_name_str,
        cad_offset_x,
        cad_offset_y,
        cad_offset_x * 304.8,
        cad_offset_y * 304.8,
        math.degrees(cad_rotation_rad),
    )


# ===========================================================================
# FAMILY SYMBOL LOOKUP
# ===========================================================================

all_symbols = list(FilteredElementCollector(doc).OfClass(FamilySymbol))
symbol_lookup = {}
symbol_lookup_ci = {}
symbol_errors = []

for s in all_symbols:
    try:
        family_name = safe_family_name(s)
        type_name = safe_symbol_name(s)
        if family_name and type_name:
            symbol_lookup[(family_name, type_name)] = s
            symbol_lookup_ci[(family_name.upper(), type_name.upper())] = (
                family_name, type_name, s
            )
    except Exception as ex:
        symbol_errors.append(str(ex))


def lookup_pair(fname, tname):
    if (fname, tname) in symbol_lookup:
        return fname, tname, symbol_lookup[(fname, tname)]
    key_ci = (str(fname).upper(), str(tname).upper())
    if key_ci in symbol_lookup_ci:
        return symbol_lookup_ci[key_ci]
    return None


def resolve_symbol(code, fname, tname):
    """Exact map, aliases, then fuzzy type name match."""
    hit = lookup_pair(fname, tname)
    if hit:
        return hit[0], hit[1], hit[2], "exact"

    for alt_fam, alt_typ in TYPE_ALIASES.get(code, []):
        hit = lookup_pair(alt_fam, alt_typ)
        if hit:
            return hit[0], hit[1], hit[2], "alias"

    want = name_key(tname) or name_key(code)
    best = None
    for family_name, type_name in symbol_lookup.keys():
        score = score_symbol_candidate(
            code, fname, tname, family_name, type_name
        )
        if best is None or score > best[0]:
            best = (score, family_name, type_name)
    if best and best[0] >= 70:
        fam, typ = best[1], best[2]
        return fam, typ, symbol_lookup[(fam, typ)], "fuzzy:{}".format(best[0])

    return None


resolved_for_json = {}
missing = []
seen_missing = set()
for g in gondolas:
    code = normalize_code(g.get("code", ""))
    if code not in TYPE_MAP:
        continue
    fname, tname = TYPE_MAP[code]
    resolved = resolve_symbol(code, fname, tname)
    if resolved is None:
        if code not in seen_missing:
            seen_missing.add(code)
            missing.append("  {} → {} / {}".format(code, fname, tname))
    else:
        resolved_for_json[code] = resolved


# ===========================================================================
# FIND EXISTING-CONDITIONS GROUND VIEW + LEVEL
# ===========================================================================
#
# Previous runs hosted on 2.0 PROPOSED because an overlay view name
# contained "existing". The user is looking at
# "1.0 EXISTING CONDITIONS - GROUND" and saw an empty CAD underlay.

all_levels = list(FilteredElementCollector(doc).OfClass(Level))
level_map = {}
for lv in all_levels:
    try:
        if lv.Name:
            level_map[str(lv.Name)] = lv
    except Exception:
        pass

all_views = list(FilteredElementCollector(doc).OfClass(ViewPlan))
target_view = None
target_level = None
view_source = ""


def _view_ok(view):
    if view is None:
        return False
    try:
        if view.IsTemplate:
            return False
    except Exception:
        pass
    try:
        return view.GenLevel is not None
    except Exception:
        return False


def _name_score(name):
    low = str(name or "").lower()
    # User typo "Exisiting" still counts.
    low = low.replace("exisiting", "existing")
    score = 0
    if "overlay" in low:
        score -= 80
    if "proposed" in low:
        score -= 50
    if "mezzanine" in low or "mezz" in low:
        score -= 30
    if "existing" in low:
        score += 40
    if "condition" in low:
        score += 25
    if "ground" in low:
        score += 25
    if "1.0" in low or "1.0" in low.replace(" ", ""):
        score += 20
    return score


# 1) The floor plan the user currently has open.
if USE_ACTIVE_PLAN_VIEW and uidoc is not None:
    try:
        active = uidoc.ActiveView
        if isinstance(active, ViewPlan) and _view_ok(active):
            if _name_score(active.Name) >= 40:
                target_view = active
                target_level = active.GenLevel
                view_source = "active existing/ground view"
            else:
                view_source = "active view skipped ({})".format(active.Name)
    except Exception:
        target_view = None
        target_level = None

# 2) Named Existing Conditions Ground plan (screenshot view).
if target_view is None:
    wanted = TARGET_VIEW_NAME.strip().lower()
    for v in all_views:
        try:
            if not _view_ok(v):
                continue
            if str(v.Name).strip().lower() == wanted:
                target_view = v
                target_level = v.GenLevel
                view_source = "TARGET_VIEW_NAME exact"
                break
        except Exception:
            pass

if target_view is None:
    ranked = []
    for v in all_views:
        try:
            if not _view_ok(v):
                continue
            ranked.append((_name_score(v.Name), v))
        except Exception:
            pass
    ranked.sort(key=lambda row: row[0], reverse=True)
    if ranked and ranked[0][0] >= 40:
        target_view = ranked[0][1]
        target_level = target_view.GenLevel
        view_source = "best existing/ground plan view"

# 3) Level by name, then a view on that level.
if target_level is None:
    target_level = level_map.get(LEVEL_NAME)
    if target_level is None:
        for name, lv in level_map.items():
            if name.strip().lower() == LEVEL_NAME.strip().lower():
                target_level = lv
                break
    if target_level is None:
        ranked_lv = []
        for name, lv in level_map.items():
            ranked_lv.append((_name_score(name), lv))
        ranked_lv.sort(key=lambda row: row[0], reverse=True)
        if ranked_lv and ranked_lv[0][0] >= 40:
            target_level = ranked_lv[0][1]

if target_level is None:
    raise Exception(
        "Could not find the Existing Conditions Ground level.\n\n"
        "Available levels:\n{}".format(
            "\n".join("  " + n for n in sorted(level_map.keys()))
        )
    )

if target_view is None:
    for v in all_views:
        try:
            if _view_ok(v) and v.GenLevel.Id == target_level.Id:
                if _name_score(v.Name) < 0:
                    continue
                target_view = v
                view_source = "first view on target level"
                break
        except Exception:
            pass

level_override_info = "View '{}' via {} | level '{}'".format(
    target_view.Name if target_view else "(none)",
    view_source or "level fallback",
    target_level.Name,
)

if REFUSE_PROPOSED_HOST:
    host_bits = " ".join(
        [
            str(target_level.Name if target_level else ""),
            str(target_view.Name if target_view else ""),
        ]
    ).lower().replace("exisiting", "existing")
    if "proposed" in host_bits and "existing" not in host_bits:
        raise Exception(
            "Refusing to host on '{}'.\n"
            "The last run put gondolas on 2.0 PROPOSED, so they are "
            "invisible in 1.0 EXISTING CONDITIONS - GROUND even though "
            "that view is open (both levels are at 0.0).\n"
            "Open 1.0 EXISTING CONDITIONS - GROUND, replace this Python "
            "node with the latest script, and run Dynamo again.".format(
                target_level.Name if target_level else "?"
            )
        )


# ===========================================================================
# BLUE GRAPHICS / EXISTING PHASE
# ===========================================================================

BLUE = Color(0, 102, 204)
color_override = OverrideGraphicSettings()
try:
    color_override.SetProjectionLineColor(BLUE)
    color_override.SetProjectionLineWeight(6)
except Exception:
    pass
try:
    color_override.SetSurfaceForegroundPatternColor(BLUE)
    color_override.SetSurfaceForegroundPatternVisible(True)
except Exception:
    pass

all_phases = list(FilteredElementCollector(doc).OfClass(Phase))
existing_phase = None
for ph in all_phases:
    try:
        name = str(ph.Name).lower()
        if name in ("existing", "existing construction", "as-built"):
            existing_phase = ph
            break
    except Exception:
        pass
if existing_phase is None and all_phases:
    existing_phase = all_phases[0]
phase_info = existing_phase.Name if existing_phase else "not set"


# ===========================================================================
# TRANSACTION
# ===========================================================================

t = Transaction(doc, "Place Existing Conditions Gondolas")
t.Start()

MANAGED_FAMILIES = {
    "Floor_Gondola",
    "Floor_Gondola_High_Bay",
    "Floor_Gondola_High_Bay-Half_Bay",
    "Wall_Gondola",
    "Wall_Gondola_High_Bay",
    "End_Panel_Decks",
    "Decks_&_Hopper",
    "End_Panel",
    "Floor_Gondola_Queuing",
    "Hotspots",
}

deleted_count = 0
all_instances = list(
    FilteredElementCollector(doc).OfClass(FamilyInstance).ToElements()
)

for inst in all_instances:
    try:
        family_name = get_instance_family_name(inst)
        if family_name not in MANAGED_FAMILIES:
            continue

        lv_param = None
        try:
            lv_param = inst.get_Parameter(BuiltInParameter.FAMILY_LEVEL_PARAM)
        except Exception:
            pass
        if lv_param is None:
            try:
                lv_param = inst.get_Parameter(
                    BuiltInParameter.INSTANCE_REFERENCE_LEVEL_PARAM
                )
            except Exception:
                pass
        if lv_param is not None:
            try:
                if lv_param.AsElementId() != target_level.Id:
                    continue
            except Exception:
                continue

        if existing_phase is not None:
            try:
                ph_param = inst.get_Parameter(BuiltInParameter.PHASE_CREATED)
                if ph_param is not None:
                    if ph_param.AsElementId() != existing_phase.Id:
                        continue
            except Exception:
                pass

        doc.Delete(inst.Id)
        deleted_count += 1
    except Exception:
        pass

doc.Regenerate()

activated = set()
for code, mapping in TYPE_MAP.items():
    fname, tname = mapping
    resolved = resolve_symbol(code, fname, tname)
    if resolved is None:
        continue
    try:
        symbol = resolved[2]
        key = (resolved[0], resolved[1])
        if not symbol.IsActive and key not in activated:
            symbol.Activate()
            activated.add(key)
    except Exception:
        pass

doc.Regenerate()


# ===========================================================================
# PLACE GONDOLAS
# ===========================================================================

placed = []
placed_ids = []
skipped = []
wall_placed = []
orientation_report = []
revealed_categories = set()
cad_rotation_deg = math.degrees(cad_rotation_rad)

for g in gondolas:
    try:
        code = normalize_code(g.get("code", ""))
        if code not in TYPE_MAP:
            skipped.append("UNKNOWN CODE: {}".format(code))
            continue

        fname, tname = TYPE_MAP[code]
        resolved = resolve_symbol(code, fname, tname)
        if resolved is None:
            close = []
            for family_name, type_name in symbol_lookup.keys():
                sc = score_symbol_candidate(
                    code, fname, tname, family_name, type_name
                )
                if sc >= 30:
                    close.append((sc, family_name, type_name))
            close.sort(reverse=True)
            hint = ""
            if close:
                hint = " | closest: " + "; ".join(
                    "{} / {} ({})".format(a, b, s) for s, a, b in close[:3]
                )
            skipped.append(
                "MISSING TYPE: {} → {} / {}{}".format(code, fname, tname, hint)
            )
            continue

        fname, tname, symbol, match_how = resolved

        x_mm = float(g.get("x", 0) or 0)
        y_mm = float(g.get("y", 0) or 0)
        x_local_ft = x_mm * MM_TO_FT
        y_local_ft = y_mm * MM_TO_FT

        if APPLY_CAD_TRANSFORM and cad_transform is not None:
            try:
                mapped = cad_transform.OfPoint(XYZ(x_local_ft, y_local_ft, 0.0))
                x_ft = mapped.X
                y_ft = mapped.Y
            except Exception:
                x_ft = cad_offset_x + x_local_ft * cad_basis_xx + y_local_ft * cad_basis_yx
                y_ft = cad_offset_y + x_local_ft * cad_basis_xy + y_local_ft * cad_basis_yy
        elif APPLY_CAD_TRANSFORM:
            x_ft = cad_offset_x + x_local_ft
            y_ft = cad_offset_y + y_local_ft
        else:
            x_ft = x_local_ft
            y_ft = y_local_ft

        z_ft = target_level.Elevation
        point = XYZ(x_ft, y_ft, z_ft)

        instance = doc.Create.NewFamilyInstance(
            point,
            symbol,
            target_level,
            StructuralType.NonStructural
        )
        placed_ids.append(instance.Id)
        try:
            lv_param = instance.get_Parameter(BuiltInParameter.FAMILY_LEVEL_PARAM)
            if lv_param is not None and not lv_param.IsReadOnly:
                lv_param.Set(target_level.Id)
        except Exception:
            pass

        if target_view is not None:
            try:
                cat = instance.Category
                if cat is not None and cat.Id not in revealed_categories:
                    if target_view.GetCategoryHidden(cat.Id):
                        target_view.SetCategoryHidden(cat.Id, False)
                    revealed_categories.add(cat.Id)
            except Exception:
                pass

        if existing_phase is not None:
            try:
                p_created = instance.get_Parameter(BuiltInParameter.PHASE_CREATED)
                if p_created is not None and not p_created.IsReadOnly:
                    p_created.Set(existing_phase.Id)
            except Exception:
                pass

        if target_view is not None:
            try:
                target_view.SetElementOverrides(instance.Id, color_override)
            except Exception:
                pass

        orientation, angle_deg, angle_source = get_orientation(
            g, cad_rotation_deg, fname
        )

        if angle_deg is not None and abs(angle_deg) > 0.0001:
            rot_origin = instance_origin(instance, point)
            axis = Line.CreateBound(
                rot_origin,
                XYZ(rot_origin.X, rot_origin.Y, rot_origin.Z + 1.0),
            )
            ElementTransformUtils.RotateElement(
                doc, instance.Id, axis, math.radians(angle_deg)
            )

        placed.append(
            "{:<24} @ ({:>9.0f}, {:>9.0f}) mm angle={:>8.3f}° {} [{} / {} via {}]".format(
                code,
                x_mm,
                y_mm,
                angle_deg if angle_deg is not None else 0.0,
                angle_source,
                fname,
                tname,
                match_how,
            )
        )
        orientation_report.append(
            "{} | orientation={} | angle={:.3f}° | source={} | axis_src={}".format(
                code,
                orientation,
                angle_deg if angle_deg is not None else 0.0,
                angle_source,
                g.get("axis_source", ""),
            )
        )

        if fname in ("Wall_Gondola", "Wall_Gondola_High_Bay"):
            eid_int = safe_element_id_value(instance.Id)
            wall_placed.append(
                "{:<24} @ ({:>9.0f}, {:>9.0f}) mm angle={:>8.3f}° id={}".format(
                    code,
                    x_mm,
                    y_mm,
                    angle_deg if angle_deg is not None else 0.0,
                    eid_int,
                )
            )
    except Exception as ex:
        skipped.append("ERROR {} :: {}".format(g.get("code", "?"), str(ex)))

if target_view is not None and placed_ids:
    try:
        from System.Collections.Generic import List as NetList
        net_ids = NetList[ElementId]()
        for eid in placed_ids:
            net_ids.Add(eid)
        target_view.UnhideElements(net_ids)
    except Exception:
        pass

t.Commit()

# Jump the open view to the first placed gondola so the trace is visible
# on 1.0 EXISTING CONDITIONS - GROUND instead of an empty CAD underlay.
zoom_info = "View was not changed."
if uidoc is not None and placed_ids:
    try:
        if target_view is not None:
            uidoc.RequestViewChange(target_view)
        uidoc.ShowElements(placed_ids[0])
        zoom_info = "Opened '{}' and zoomed to first placed gondola.".format(
            target_view.Name if target_view else target_level.Name
        )
    except Exception as ex:
        zoom_info = "Could not zoom: {}".format(str(ex))


# ===========================================================================
# REPORT
# ===========================================================================

sep = "=" * 75
lines = [
    "",
    sep,
    " EXISTING CONDITIONS — GONDOLA PLACEMENT",
    sep,
    "",
    "Total JSON items       : {}".format(len(gondolas)),
    "Placed                 : {}".format(len(placed)),
    "Skipped                : {}".format(len(skipped)),
    "Deleted previous       : {}".format(deleted_count),
    "",
    "WHERE TO LOOK",
    "  Open this view       : {}".format(
        target_view.Name if target_view else "(no plan view)"
    ),
    "  {}".format(zoom_info),
    "  Previous run hosted on 2.0 PROPOSED — that is why",
    "  1.0 EXISTING CONDITIONS - GROUND looked empty.",
    "",
    "LEVEL",
    "  Level used           : {}".format(target_level.Name),
    "  Elevation            : {:.3f} ft".format(target_level.Elevation),
    "  Level note           : {}".format(
        level_override_info if level_override_info else "Matched LEVEL_NAME"
    ),
    "",
    "PHASE",
    "  Phase used           : {}".format(phase_info),
    "",
    "CAD TRANSFORM",
    "  {}".format(cad_offset_info),
    "  Applied              : {}".format(APPLY_CAD_TRANSFORM),
    "",
    "ORIENTATION",
    "  JSON angle enabled   : {}".format(USE_JSON_ANGLE),
    "  Angle sign           : {}".format(ANGLE_SIGN),
    "  Angle offset         : {:.3f}°".format(ANGLE_OFFSET_DEG),
    "",
    "ALL CAD IMPORTS:",
]

if all_cad_found:
    lines.extend(all_cad_found)
else:
    lines.append("    NONE FOUND")

lines.extend(["", "ORIENTATION USED FOR EACH ITEM:"])
if orientation_report:
    lines.extend(["    " + x for x in orientation_report])
else:
    lines.append("    NONE")

if wall_placed:
    lines.extend(["", "WALL GONDOLAS PLACED: {}".format(len(wall_placed))])
    lines.extend(["    " + x for x in wall_placed])

if missing:
    lines.extend(["", "MISSING REVIT TYPES:"])
    lines.extend(["    " + x for x in missing])

if symbol_errors:
    lines.extend(["", "SYMBOL LOOKUP WARNINGS:"])
    lines.extend(["    " + x for x in symbol_errors])

if skipped:
    lines.extend(["", "SKIPPED / ERRORS:"])
    lines.extend(["    " + x for x in skipped])

lines.extend(["", "PLACED GONDOLAS:"])
lines.extend(["    " + x for x in placed])
lines.extend(["", sep, ""])

OUT = "\n".join(lines)
